cd /mmfs1/gscratch/krishna/mayank/clip_clone/open_clip/src
torchrun --nproc_per_node 2 --master_port 3234 -m training.main \
    --model "ViT-B-16" \
    --train-data "/mmfs1/data/yfcc-tmp/cc_3m/train_shards/shard_{000000..003318}.tar" \
    --imagenet-val "/mmfs1/data/yfcc-tmp/imagenet/val/" \
    --dataset-type webdataset \
    --precision amp \
    --gather-with-grad \
    --local-loss \
    --force_byol_clip \
    --byol_beta_base_ema 0.99 \
    --batch-size 256 \
    --accum-freq 2 \
    --workers 4 \
    --epochs 40 \
    --warmup 2000 \
    --zeroshot-frequency 2 \
    --seed 0 \
    --report-to 'wandb' \
    --wandb-project-name "byol_clip_training" \
    --logs "/mmfs1/gscratch/krishna/mayank/clip_clone/open_clip/src/logs/byol_clip" \
    --name "byol_asym_clip_orig_b256_accum_2_ep40_emabase0_99_lossWgt_1k_update_after_optimizerstep" 
