cd /mmfs1/gscratch/krishna/mayank/clip_clone/open_clip/src
torchrun --nproc_per_node 2 -m training.main \
    --model "ViT-B-16" \
    --train-data "/mmfs1/data/yfcc-tmp/cc_3m/train_shards/shard_{000000..003318}.tar" \
    --imagenet-val "/mmfs1/data/yfcc-tmp/imagenet/val/" \
    --dataset-type webdataset \
    --precision amp \
    --gather-with-grad \
    --local-loss \
    --batch-size 512 \
    --cosinereg 0.001 \
    --seed 0 \
    --workers 6 \
    --warmup 500 \
    --epochs 128 \
    --zeroshot-frequency 2 \
    --report-to 'wandb' \
    --wandb-project-name "threshold_finetuning" \
    --resume /mmfs1/gscratch/krishna/mayank/clip_clone/checkpoints/reg0.00/epoch_32.pt \
    --logs "/mmfs1/gscratch/krishna/mayank/clip_clone/open_clip/src/logs/threshold_finetuning" \
    --name ViT-B-16-threshold_finetuning_0_00_32ep_0_001_128ep 